# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

trigger:
  batch: 'true'
  paths:
    exclude: ['CONTRIBUTING.md']

resources:
  repositories:
    - repository: coretemplate
      type: git
      name: WizPipelines/core-template

extends:
  template: main.yml@coretemplate
  parameters:
    technology: 'node-package'
    npmCustomEndpoint: 'npmjs'
    npmRunBuild: true
    npmNodeVersion: '16.x'
